coverage:
  status:
    project:
      default: off
      frontend:
        flags: frontend
        target: 90
flags:
  frontend:
    paths:
      - src/
    tests:
      paths:
        - tests/
comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
